[[bun]]
arch = "aarch64"
git-tree-sha1 = "bfbe0e4eb88e7cc713beaa69aa6fb8608ae2278e"
os = "macos"

    [[bun.download]]
    sha256 = "5caa9f2d59adb147426ef75d3aae69f6547abf043d972ce1871761df78ee0dad"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.1.34%2B0/bun-1.1.34+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "6030d93e753e1e3d0b75209ac7bb6176a3c76b2c"
os = "macos"

    [[bun.download]]
    sha256 = "f3be6afa994ba0f76949c47f0a81ac152f83fa9458b05db026de117796aaed34"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.1.34%2B0/bun-1.1.34+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "c40b7bcbb8f9b5eba17b49b98d121f33710976c7"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "90bb5659444c23ffe8b3d3743c5a17a40231bc0acbd0eb1a9efce5a1c1bfd00d"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.1.34%2B0/bun-1.1.34+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "37f181c0517b5b05db7211e134e71944a3faa934"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "e7309fbb664b657c11c3c9f40b749a5ae59b26613046cdf48b694b950f6b21a4"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.1.34%2B0/bun-1.1.34+0-x86_64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "39b646e010561cb50c5020173a9da60c62e30bbc"
os = "windows"

    [[bun.download]]
    sha256 = "787f914eaf2d37718e20baeb44e618626b2339adbc7049c11fbc3490970cdf76"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.1.34%2B0/bun-1.1.34+0-x86_64-w64-mingw32.tar.gz"
