[[bun]]
arch = "aarch64"
git-tree-sha1 = "b84bfd5c4be5ca2a38f074c3311dbf69c40642d2"
os = "macos"

    [[bun.download]]
    sha256 = "2b5b3878201abe0f06eae01fb8b466eda9d41ce9a4d2e751d2e18512f152ed3d"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.2.0%2B0/bun-1.2.0+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "8085f06365da0d532ca88bf96b36b6c906fedb22"
os = "macos"

    [[bun.download]]
    sha256 = "5bcb726894722ec213d58a07eda54a26c3b03a5261ed00b2f35979f6bb14704c"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.2.0%2B0/bun-1.2.0+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "8461a48de41f5d2e9fd7dddd90816217eed23177"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "ce5c4054be251f55345a4b649893a38f9388db461f70b5b5a6ecb383f68a1e3a"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.2.0%2B0/bun-1.2.0+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "4515b325c6ed671f4cfe15410bca44db08b8e7be"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "6e9f0d621bade28482a2bf02e7e768e8f45831bdeba815d88d31a07395448a03"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.2.0%2B0/bun-1.2.0+0-x86_64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "f2eeb8b704cd03b276988c04785a8890db76d412"
os = "windows"

    [[bun.download]]
    sha256 = "248ef535a257dff38186b8421acb2aecb81172e9c868462e6001a3e6e4c50b55"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.2.0%2B0/bun-1.2.0+0-x86_64-w64-mingw32.tar.gz"
