[[bun]]
arch = "aarch64"
git-tree-sha1 = "1aee27c81455f5a9ed427b678ef60717f63f5a01"
os = "macos"

    [[bun.download]]
    sha256 = "8037a9e438da69c6db4ed8c5aff10c4166bbc7a854e770871e283e1a13eed352"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.17%2B0/bun-1.0.17+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "054277e93f8a2d42cce976e7d09e12e805a10242"
os = "macos"

    [[bun.download]]
    sha256 = "1478ac288538b3bda3b40b55c3baa45b5a535bbdf6c5715153b6e23ea3dc652b"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.17%2B0/bun-1.0.17+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "b0d78070e47183d12e1dbc9523bc4d92a811246e"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "afac9b2136f8a7542d76ffa2cc79bc458cae2e10d1be1618f69b8e642dd47fac"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.17%2B0/bun-1.0.17+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "cc638ff1fb4308d24109ebf70e415950ded83399"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "59dcd59ea5d42ceef79ebc1df0fa8c919fb81512158801707b1c05e5153fa237"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.17%2B0/bun-1.0.17+0-x86_64-linux-gnu.tar.gz"
