[[bun]]
arch = "aarch64"
git-tree-sha1 = "2da1499d827950f7ac87eb05a690c360e7bb3d64"
os = "macos"

    [[bun.download]]
    sha256 = "a487d43f85166ea5e8ec57359035e022f81dec1a8ba6fea50a0e53834587a7ff"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.19%2B0/bun-1.0.19+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "83fba6abf67249cdd22e48767cf840a011f30876"
os = "macos"

    [[bun.download]]
    sha256 = "f5cdd42eb6522b0f641a949feba2bfa66f8b3fbe31cae4759a84bcfc0529cca4"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.19%2B0/bun-1.0.19+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "bff54282c6095eb1a2af5757a28623b543bbb0e2"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "1f8728f504ee10e8b90c6ccd5c1f027a93d4ec6e369366d3b6073d8ea3d063ee"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.19%2B0/bun-1.0.19+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "50ee1a4f6d1e8e46f19418f3ac268bc48babc570"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "9542fc4deb432b2d5d7ff34cc74f4db8c5b38ba62e32aa8e004ec543efe9954a"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.19%2B0/bun-1.0.19+0-x86_64-linux-gnu.tar.gz"
