[[bun]]
arch = "aarch64"
git-tree-sha1 = "e2fe6dfd4fe4271c300976c617142909c61d2ae8"
os = "macos"

    [[bun.download]]
    sha256 = "801346430af3af9839091d89a44b3439b3dd00bcb72aefa3d85b305110e58d4b"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.33%2B0/bun-1.0.33+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "a01ba60ebe5601b80fd52fe7237a57aff77b6e73"
os = "macos"

    [[bun.download]]
    sha256 = "6c704f7790f0d2244807e5b2706b7d4dcb912117a04968813d4b5043e4e6f0fa"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.33%2B0/bun-1.0.33+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "77760cadec733280054779f760cf53c3a1290cf2"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "8513bfe4a4d3f8cdd8fa0ad7c2be33a3b906596bbf4d8b806116d210f642fc51"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.33%2B0/bun-1.0.33+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "0cb2d93fbd59a540329a52a901ee1f9a5dfa402f"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "db07231b91c2c6eab7656f17acb1992d46de75eccea0cb1791aebe68e23bfdd0"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.33%2B0/bun-1.0.33+0-x86_64-linux-gnu.tar.gz"
