[[bun]]
arch = "aarch64"
git-tree-sha1 = "8c9ff1e19eba5323790565f3986ea491bbfd2b0e"
os = "macos"

    [[bun.download]]
    sha256 = "6d3d6c6fc6b66c20c60f1bb27d7ccef8fa4e587013a02e3e637b4861914380b9"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.16%2B0/bun-1.0.16+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "4f1ebc17ece896aefbe89d5fd2c054096138c757"
os = "macos"

    [[bun.download]]
    sha256 = "7f828617f3455aec58d6327416f40f301c9f4fe10103c0c7b4e6d005d2a0d4f4"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.16%2B0/bun-1.0.16+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "fc227a60ed14a7f1d63402ed62b88d7acbf61309"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "67a13ca346541f23cb8b75f9ff7e854c4d501662f2baf500e5188a199b63c163"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.16%2B0/bun-1.0.16+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "5e5f15c5de9d9bba25858cceb8063a704ebe5c29"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "f40b65be769ebcffaf30dce39bbc6d58fa78fbc1a7a98d594be9461ca54ed303"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.16%2B0/bun-1.0.16+0-x86_64-linux-gnu.tar.gz"
