[[bun]]
arch = "aarch64"
git-tree-sha1 = "f739ccb8d1f2074e8059453b09d5c5c34218c919"
os = "macos"

    [[bun.download]]
    sha256 = "44ec820e6ad07d837981e5e5dd38776bef9bd2ef435eed5fcb8ba43542a5a1df"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.15%2B0/bun-1.0.15+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "cc1179197eb5518023d53fa9c7de8a5bfd81f0d0"
os = "macos"

    [[bun.download]]
    sha256 = "68fe45f9c7cac28792f29ab53fead295b5a0e2e6bc44dcb7215288195ba5375c"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.15%2B0/bun-1.0.15+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "975f127ed695ca761c01c978578a9e06413df138"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "1281bad051bd7d21dbe2fd56498e981d58ca13af258e1c99f6970dcc060142e4"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.15%2B0/bun-1.0.15+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "d7fd866e1e9dfd10743ee4bec511e2024ab2e91c"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "e5f182c6ad05548401f76f326f82f5d48f99c5abbb8f865ef6d42a8f86a7432f"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.15%2B0/bun-1.0.15+0-x86_64-linux-gnu.tar.gz"
