[[bun]]
arch = "aarch64"
git-tree-sha1 = "5b91fd73308c1a79c745b97e1302fbbb910dc469"
os = "macos"

    [[bun.download]]
    sha256 = "4cec2964a91261ba0d86ab7e0c2f344538744564f573fb7d2ad7ed82534b21a2"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.18%2B0/bun-1.0.18+0-aarch64-apple-darwin14.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "c642aa0b90f9ce09b4d0ddfd10f8258b37ecb5e8"
os = "macos"

    [[bun.download]]
    sha256 = "f4e19a7189f2b6a12e611ff449eff140e72a29b8108f04e751893f9814b5cafd"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.18%2B0/bun-1.0.18+0-x86_64-apple-darwin14.tar.gz"
[[bun]]
arch = "aarch64"
git-tree-sha1 = "973e74556bacf8154232cab46b215b1788e7fd53"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "a758da7020c37e41a39fe1634ef780cbbf9ef0d29ad339fad5d94bd67f57de19"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.18%2B0/bun-1.0.18+0-aarch64-linux-gnu.tar.gz"
[[bun]]
arch = "x86_64"
git-tree-sha1 = "5ae6a057b813fb22e9af1a664bfd7ce856c92357"
libc = "glibc"
os = "linux"

    [[bun.download]]
    sha256 = "2871ee9f609851c60473c976a227352c15679db0615d784ec528cd2dca3a6ef7"
    url = "https://github.com/MichaelHatherly/BundledWebResources.jl/releases/download/bun-v1.0.18%2B0/bun-1.0.18+0-x86_64-linux-gnu.tar.gz"
